server:
  port: 8082
spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Waheguru9898!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

welcome:
  message: Hi from Dev!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "beans,env"

#---
#
#spring:
#  profiles: qa
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/dcbapp-qa
#    password: Waheguru9898!
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#
#welcome:
#  message: Hi from QA!
#
---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: Waheguru9898!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

welcome:
  message: Hi from Prod!